categories:
  - Imaging
description: Convert DICOM to TIFF and vise-versa
long_description: This tools converts a DICOM file to a TIFF image, or vise-versa.
name: pydicom
owner: imgteam
homepage_url: https://github.com/bmcv
remote_repository_url: https://github.com/BMCV/galaxy-image-analysis/tree/master/tools/pydicom/
